[project]
name = "pycfd"
version = "0.1.0"
description = "Bac à sable en Python pour expérimenter des schémas numériques pour la CFD. Ce code n'a pas pour but d'être utilisé pour de vraies simulations."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.0",
]
